name: sha2

on:
  pull_request:
    paths:
      - ".github/workflows/sha2.yml"
      - "sha2/**"
      - "Cargo.*"
  push:
    branches: master

defaults:
  run:
    working-directory: sha2

env:
  RUSTFLAGS: "-Dwarnings"
  CARGO_INCREMENTAL: 0

jobs:
  # Builds for no_std platforms
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
        target:
          - thumbv7em-none-eabi
          - wasm32-unknown-unknown
    steps:
      - uses: actions/checkout@v2
      - uses: risc0/risc0/.github/actions/rustup@main
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          targets: ${{ matrix.target }}
          override: true
      - run: cargo build --no-default-features --target ${{ matrix.target }}

  # Linux tests
  linux:
    strategy:
      matrix:
        include:
          # 32-bit Linux/x86
          - target: i686-unknown-linux-gnu
            rust: stable
            deps: sudo apt update && sudo apt install gcc-multilib

          # 64-bit Linux/x86_64
          - target: x86_64-unknown-linux-gnu
            rust: stable

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: risc0/risc0/.github/actions/rustup@main
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          targets: ${{ matrix.target }}
          override: true
      - run: ${{ matrix.deps }}
      - run: cargo test --target ${{ matrix.target }} --no-default-features
      - run: cargo test --target ${{ matrix.target }}
      - run: cargo test --target ${{ matrix.target }} --features asm
      - run: cargo test --target ${{ matrix.target }} --all-features

  # macOS tests
  macos:
    strategy:
      matrix:
        rust:
          - stable

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: risc0/risc0/.github/actions/rustup@main
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          targets: x86_64-apple-darwin
          override: true
      - run: cargo test --no-default-features
      - run: cargo test
      - run: cargo test --features asm

  # TODO: remove on MSRV bump to 1.57 or higher
  test-msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: risc0/risc0/.github/actions/rustup@main
        with:
          profile: minimal
          toolchain: 1.41.0
          override: true
      - run: cargo test --no-default-features
      - run: cargo test
